"""Added user functionality

Revision ID: 3afa55c31ac7
Revises: 43d6f9edbcb5
Create Date: 2024-11-21 14:16:44.515467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afa55c31ac7'
down_revision = '43d6f9edbcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('isApproved', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    # ### end Alembic commands ###
