"""all migrations

Revision ID: 43d6f9edbcb5
Revises: 
Create Date: 2024-10-22 11:56:03.633470

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '43d6f9edbcb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('url', sa.Text(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('type', sa.Text(), nullable=False),
                    sa.Column('isLink', sa.Boolean(), nullable=True),
                    sa.Column('createdAt', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updatedAt', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('horses',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('birth_date', sa.DateTime(), nullable=False),
                    sa.Column('sex', sa.Text(), nullable=False),
                    sa.Column('race', sa.Text(), nullable=False),
                    sa.Column('fur', sa.Text(), nullable=False),
                    sa.Column('origin', sa.Enum('Compra', 'Donacion',
                              name='horse_origin'), nullable=False),
                    sa.Column('entry_date', sa.DateTime(), nullable=False),
                    sa.Column('headquarter', sa.Text(), nullable=False),
                    sa.Column('jya_type', sa.Enum('Hipoterapia', 'Monta Terapéutica', 'Deporte Ecuestre', 'Adaptado',
                                                  'Actividades Recreativas', 'Equitación', name='jya_type'),
                              nullable=False),
                    sa.Column('createdAt', sa.DateTime(), nullable=True),
                    sa.Column('updatedAt', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('people',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('surname', sa.Text(), nullable=False),
                    sa.Column('dni', sa.BigInteger(), nullable=False),
                    sa.Column('address', sa.Text(), nullable=False),
                    sa.Column('telephone', sa.Text(), nullable=False),
                    sa.Column('emergency_contact', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('permissions',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('horse_files',
                    sa.Column('horse_id', sa.BigInteger(), nullable=False),
                    sa.Column('file_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
                    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
                    sa.PrimaryKeyConstraint('horse_id', 'file_id')
                    )
    op.create_table('jya',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('person_id', sa.BigInteger(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('birth_date', sa.DateTime(), nullable=False),
                    sa.Column('birth_place', sa.Text(), nullable=True),
                    sa.Column('granted', sa.Boolean(), nullable=False),
                    sa.Column('grant_percentage', sa.Float(), nullable=True),
                    sa.Column('behind_payment', sa.Boolean(), nullable=False),
                    sa.Column('createdAt', sa.DateTime(), nullable=True),
                    sa.Column('updatedAt', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('members',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('person_id', sa.BigInteger(), nullable=False),
                    sa.Column('email', sa.Text(), nullable=False),
                    sa.Column('locality', sa.Text(), nullable=False),
                    sa.Column('profession', sa.Text(), nullable=False),
                    sa.Column('job_position', sa.Text(), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('medical_insurance', sa.Text(), nullable=False),
                    sa.Column('insurance_number', sa.Text(), nullable=False),
                    sa.Column('job_condition', sa.Text(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('createdAt', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updatedAt', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('role_permissions',
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('permission_id',
                              sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['permission_id'], ['permissions.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('role_id', 'permission_id')
                    )
    op.create_table('charges',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('member_id', sa.BigInteger(), nullable=True),
                    sa.Column('jya_id', sa.BigInteger(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('payment_method', sa.Text(), nullable=False),
                    sa.Column('amount', sa.Numeric(), nullable=False),
                    sa.Column('observations', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['jya_id'], ['jya.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('horse_rider_association',
                    sa.Column('member_id', sa.BigInteger(), nullable=False),
                    sa.Column('horse_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('member_id', 'horse_id')
                    )
    op.create_table('horse_trainer_association',
                    sa.Column('member_id', sa.BigInteger(), nullable=False),
                    sa.Column('horse_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('member_id', 'horse_id')
                    )
    op.create_table('jya_files',
                    sa.Column('jya_id', sa.BigInteger(), nullable=False),
                    sa.Column('file_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
                    sa.ForeignKeyConstraint(['jya_id'], ['jya.id'], ),
                    sa.PrimaryKeyConstraint('jya_id', 'file_id')
                    )
    op.create_table('jya_professional_association',
                    sa.Column('jya_id', sa.BigInteger(), nullable=False),
                    sa.Column('member_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['jya_id'], ['jya.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('jya_id', 'member_id')
                    )
    op.create_table('member_files',
                    sa.Column('member_id', sa.BigInteger(), nullable=False),
                    sa.Column('file_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('member_id', 'file_id')
                    )
    op.create_table('payments',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('member_id', sa.BigInteger(), nullable=True),
                    sa.Column('amount', sa.Numeric(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('type', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('email', sa.Text(), nullable=False),
                    sa.Column('alias', sa.Text(), nullable=False),
                    sa.Column('password', sa.Text(), nullable=True),
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('member_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('messages',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              nullable=False, default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=False, default=sa.func.now(),
                              onupdate=sa.func.now()),
                    sa.Column('full_name', sa.String(150), nullable=False),
                    sa.Column('email', sa.String(250), nullable=False),
                    sa.Column('body', sa.String(150), nullable=True),
                    sa.Column('status', sa.Enum('Pendiente', 'Contestada', name='status'), nullable=False,
                              default='Pendiente'),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('publications',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('publication_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              nullable=False, default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=False, default=sa.func.now(),
                              onupdate=sa.func.now()),
                    sa.Column('title', sa.String(150), nullable=False),
                    sa.Column('summary', sa.String(250), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(),
                              sa.ForeignKey('users.id'), nullable=False),
                    sa.Column('status', sa.Enum('Borrador', 'Archivada', 'Publicada', name='publication_status'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('payments')
    op.drop_table('member_files')
    op.drop_table('jya_professional_association')
    op.drop_table('jya_files')
    op.drop_table('horse_trainer_association')
    op.drop_table('horse_rider_association')
    op.drop_table('charges')
    op.drop_table('role_permissions')
    op.drop_table('members')
    op.drop_table('jya')
    op.drop_table('horse_files')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('people')
    op.drop_table('horses')
    op.drop_table('files')
    # Drop enums
    op.execute('DROP TYPE status')
    op.execute('DROP TYPE horse_origin')
    op.execute('DROP TYPE jya_type')
    op.execute('DROP TYPE publication_status')
    # ### end Alembic commands ###
