"""Added nullable member id and role id

Revision ID: 5181c9495da0
Revises: 3afa55c31ac7
Create Date: 2024-11-21 14:24:16.974179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5181c9495da0'
down_revision = '3afa55c31ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
                              existing_type=sa.BIGINT(),
                              nullable=True)
        batch_op.alter_column('member_id',
                              existing_type=sa.BIGINT(),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('member_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)
        batch_op.alter_column('role_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)

    # ### end Alembic commands ###
