"""fixed names

Revision ID: c57dda2500b2
Revises: 5181c9495da0
Create Date: 2024-11-21 15:30:55.165776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57dda2500b2'
down_revision = '5181c9495da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_approved', sa.Boolean(), nullable=False))
        batch_op.drop_column('isApproved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('isApproved', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
