version: "3.7"
services:
  postgres-db:
    image: postgres:16.4
    container_name: postgres-db
    environment:
      POSTGRES_USER: equinoterapia
      POSTGRES_PASSWORD: equinoterapia
      POSTGRES_DB: cedica
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"